build: false

environment:
  PYTHON_HOME: "C:\\Python37"
  CONAN_LOGIN_USERNAME: "admin"
  CONAN_PASSWORD:
      secure: g+1lNdgrCLmyKNf3KvbHSln5A1H7BsVhsMsIbwgo+UU=
  VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
  CONAN_UPLOAD: https://lkeb-artifactory.lumc.nl/artifactory/api/conan/conan-local
  CONAN_REMOTE: lkebconan
  CONAN_STABLE_BRANCH_PATTERN: "release/*|master"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  BUILD_SHARED: True

  matrix:

# VS 2017

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

       CONAN_VISUAL_VERSIONS: 15
       CONAN_ARCHS: x86_64
       CONAN_BUILD_TYPES: Release
       CONAN_VISUAL_RUNTIMES: MD
       REPLACE_CMAKE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\"

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
       CONAN_VISUAL_VERSIONS: 15
       CONAN_ARCHS: x86_64
       CONAN_BUILD_TYPES: Debug
       CONAN_VISUAL_RUNTIMES: MDd
       REPLACE_CMAKE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\"

# VS 2019

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
       CONAN_VISUAL_VERSIONS: 16
       CONAN_ARCHS: x86_64
       CONAN_BUILD_TYPES: Release
       CONAN_VISUAL_RUNTIMES: MD

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
       CONAN_VISUAL_VERSIONS: 16
       CONAN_ARCHS: x86_64
       CONAN_BUILD_TYPES: Debug
       CONAN_VISUAL_RUNTIMES: MDd


install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install cmake --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory
  - for /f "delims=" %%i in ('conan config home') do set CONANPEMHOME=%%i
  - type cert.pem >> %CONANPEMHOME%\cacert.pem
  - git submodule update --init --recursive

skip_commits:
    files:
        - README.md
        - travis.yml

notifications:
  - provider: Email
    to:
        - b.van_lew@lumc.nl
    subject: Test HDILib {{status}}
    message: "URL is {{buildUrl}} Commit ID {{commitId}}. Messages {{jobs.0.messages.0.message}}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

build_script:
  - .\\.ci\\fix_cmake.bat
  - python build.py


