build: false

environment:
  PYTHON_HOME: "C:\\Python37"
  CONAN_LOGIN_NAME: "admin"
  CONAN_PASSWORD:
      secure: g+1lNdgrCLmyKNf3KvbHSln5A1H7BsVhsMsIbwgo+UU=
  VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
  CONAN_UPLOAD: https://lkeb-artifactory.lumc.nl/artifactory/api/conan/conan-local
  CONAN_REMOTE: lkebconan
  CONAN_STABLE_BRANCH_PATTERN: "release/*|master"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  BUILD_SHARED: True

  matrix:

# VS 2017

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

       CONAN_VISUAL_VERSIONS: 15
       CONAN_ARCHS: x86_64
       CONAN_BUILD_TYPES: "Release,Debug"
       #CONAN_VISUAL_RUNTIMES: "MD,MDd"
       REPLACE_CMAKE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\"

# VS 2019

     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
       CONAN_VISUAL_VERSIONS: 16
       CONAN_ARCHS: x86_64
       #CONAN_VISUAL_RUNTIMES: MD

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install cmake --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory
  - for /f "delims=" %%i in ('conan config home') do set CONANPEMHOME=%%i
  - type cert.pem >> %CONANPEMHOME%\cacert.pem
  - git submodule update --init --recursive

skip_commits:
    files:
        - README.md
        - travis.yml

notifications:
  - provider: Email
    to:
        - b.van_lew@lumc.nl
    subject: Test HDILib {{status}}
    message: "URL is {{buildUrl}} Commit ID {{commitId}}. Messages {{jobs.0.messages.0.message}}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

build_script:
  - .\\.ci\\fix_cmake.bat
  # configure the build action
  - conan remote add %CONAN_REMOTE% %CONAN_UPLOAD%
  - conan profile new action_build
  - conan profile update settings.os=Windows action_build
  - conan profile update settings.os_build=Windows action_build
  - conan profile update settings.arch=%CONAN_ARCHS% action_build
  - conan profile update settings.arch_build=%CONAN_ARCHS% action_build
  - conan profile update settings.compiler="Visual Studio" action_build
  - conan profile update settings.compiler.version=%CONAN_VISUAL_VERSIONS% action_build
  #- conan profile update options.shared="True" action_build
  - set CONAN_BASE_PROFILE=action_build
  - set SAVE_PATH=%PATH%
  - ps: ./.ci\set_appveyor_conan_reference.ps1 HDILib biovault/stable
  - refreshenv
  - set PATH=%SAVE_PATH%
  - echo %CONAN_REFERENCE%
  # configure for the multi package
  - conan install . -s build_type=Release -s compiler.runtime=MD --profile action_build
  - conan install . -s build_type=Debug -s compiler.runtime=MDd --profile action_build
  # test_package is release only
  - cd test_package
  - conan install . -s build_type=Release -s compiler.runtime=MD --profile action_build
  - cd ..
  - conan create . %CONAN_REFERENCE% --profile action_build
  # - python build.py

on_success:
  - conan user -p %CONAN_PASSWORD% %CONAN_LOGIN_NAME% -r lkeb-artifactory
  - conan upload -r lkeb-artifactory --all --force -c $CONAN_REFERENCE


